version: '3'
services:
  16-bits-back-end:
    image: "avvaru-viswanath/spring-react-demo-app-be:0.0.3"
    container_name: avvaru-viswanath-back-end
    ports:
      - "8080:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=default, in-memory
  16-bits-front-end:
    image: "avvaru-viswanath/spring-react-demo-app-fe:0.0.3"
    container_name: avvaru-viswanath-front-end
    ports:
      - "3000:3000"
